name: 'AWS IAM Minter'
description: 'Mint AWS STS credentials based on github token verification'
author: 'Netlibs'
inputs: 
  endpoint:
    description: 'The minter endpoint'
    required: true
  token:
    description: 'The GitHub token'
    required: true
  role:
    description: 'The AWS Role ARN to request be assumed'
    required: false
  profile:
    description: 'The AWS profile token'
    required: true
    default: 'default'
  region:
    description: 'The AWS region'
    required: true
    default: us-west-2
  actor:
    description: 'The actor'
    required: true
    default: 'github-actions'
  project:
    description: 'The GitHub full project (org/project) to mint credential for'
    default: ${{ github.repository }}
    required: true
runs:
  using: 'node16'
  main: 'index.js'
