name: 'IAM Minter'
description: 'Mint AWS STS credentials based on github token verification'
author: 'GitHub'
inputs: 
  endpoint:
    description: 'The minter endpoint'
    required: true
  token:
    description: 'The GitHub token'
    required: true
  project:
    description: 'The GitHub full project (org/project) to mint credential for'
    default: ${{ github.repository }}
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
